// AUTO-GENERATED by scripts/fetch-dart-financials.mjs — GitHub Actions 또는 본인 PC 에서 갱신
// 빌드시 placeholder. DART 가 Vercel IP 차단하므로 비차단 IP 에서 미리 받아둠.
export const DART_FINANCIAL_DATA: Record<
  string,
  { roe: number | null; operatingMargin: number | null; debtRatio: number | null; reportYear: number }
> = {};
