// AUTO-GENERATED by scripts/fetch-sec-filings.py — GitHub Actions 에서 갱신
// 빌드시 placeholder.
export const SEC_FILINGS_DATA: Record<
  string,
  Array<{ date: string; form: string; url: string }>
> = {};
