// 주요 해외 종목 한글 표기 매핑. 이름이 있으면 토스처럼 한글로 보여주고,
// 없으면 원본 영문명 유지. 검색은 한글/영문/티커 셋 다로 가능하게 함.

export const US_KR_NAMES: Record<string, string> = {
  // --- Tech 대형주 ---
  AAPL: "애플",
  MSFT: "마이크로소프트",
  NVDA: "엔비디아",
  GOOGL: "알파벳 A (구글)",
  GOOG: "알파벳 C (구글)",
  AMZN: "아마존",
  META: "메타 (페이스북)",
  TSLA: "테슬라",
  AVGO: "브로드컴",
  ORCL: "오라클",
  ADBE: "어도비",
  CRM: "세일즈포스",
  CSCO: "시스코",
  INTC: "인텔",
  AMD: "AMD",
  QCOM: "퀄컴",
  TXN: "텍사스인스트루먼트",
  IBM: "IBM",
  AMAT: "어플라이드머티리얼즈",
  MU: "마이크론",
  ASML: "ASML",
  TSM: "TSMC (대만반도체)",
  SMCI: "슈퍼마이크로컴퓨터",
  DELL: "델",
  HPQ: "HP",
  NOW: "서비스나우",
  SNOW: "스노우플레이크",
  MDB: "몽고DB",
  DDOG: "데이터독",
  NET: "클라우드플레어",
  OKTA: "옥타",
  TEAM: "아틀라시안",
  WDAY: "워크데이",
  PANW: "팔로알토 네트웍스",
  CRWD: "크라우드스트라이크",
  ZS: "지스케일러",
  FTNT: "포티넷",
  ANET: "아리스타 네트웍스",
  MRVL: "마벨 테크놀로지",
  NXPI: "NXP 반도체",
  ADI: "아날로그 디바이스",
  LRCX: "램 리서치",
  KLAC: "KLA",
  MCHP: "마이크로칩",
  ON: "온세미컨덕터",
  ARM: "ARM",
  INTU: "인튜이트",
  MELI: "메르카도리브레",

  // --- 소비 / 리테일 ---
  WMT: "월마트",
  HD: "홈디포",
  LOW: "로우스",
  COST: "코스트코",
  TGT: "타겟",
  KO: "코카콜라",
  PEP: "펩시코",
  PG: "P&G",
  UL: "유니레버",
  MCD: "맥도날드",
  SBUX: "스타벅스",
  YUM: "얌브랜즈",
  NKE: "나이키",
  LULU: "룰루레몬",
  DIS: "디즈니",
  NFLX: "넷플릭스",
  CMG: "치폴레",

  // --- 금융 ---
  BRK: "버크셔해서웨이",
  "BRK-A": "버크셔해서웨이 A",
  "BRK-B": "버크셔해서웨이 B",
  V: "비자",
  MA: "마스터카드",
  JPM: "JP모건",
  BAC: "뱅크오브아메리카",
  WFC: "웰스파고",
  C: "씨티그룹",
  GS: "골드만삭스",
  MS: "모건스탠리",
  BLK: "블랙록",
  SCHW: "찰스슈왑",
  AXP: "아메리칸익스프레스",
  SPGI: "S&P글로벌",
  COF: "캐피탈원",
  PYPL: "페이팔",
  SQ: "블록 (스퀘어)",
  COIN: "코인베이스",
  HOOD: "로빈후드",
  SOFI: "소파이",

  // --- 헬스케어 / 바이오 ---
  LLY: "일라이릴리",
  UNH: "유나이티드헬스",
  JNJ: "존슨앤존슨",
  ABBV: "애브비",
  MRK: "머크",
  PFE: "화이자",
  TMO: "써모피셔",
  ABT: "애보트",
  DHR: "다나허",
  BMY: "브리스톨마이어스",
  AMGN: "암젠",
  GILD: "길리어드",
  REGN: "리제네론",
  VRTX: "버텍스",
  MRNA: "모더나",
  BNTX: "바이온텍",
  NVO: "노보노디스크",
  AZN: "아스트라제네카",
  LLY2: "일라이릴리",

  // --- 자동차 / 항공 / 운송 ---
  F: "포드",
  GM: "GM",
  RIVN: "리비안",
  LCID: "루시드",
  NIO: "니오",
  XPEV: "샤오펑",
  LI: "리오토",
  BA: "보잉",
  LMT: "록히드마틴",
  GE: "GE",
  RTX: "RTX (레이시온)",
  NOC: "노스롭그루먼",
  UPS: "UPS",
  FDX: "FedEx",
  UNP: "유니언퍼시픽",
  CSX: "CSX",
  UAL: "유나이티드항공",
  DAL: "델타항공",
  LUV: "사우스웨스트항공",
  UBER: "우버",
  LYFT: "리프트",
  ABNB: "에어비앤비",
  BKNG: "부킹닷컴",

  // --- 통신 / 미디어 ---
  T: "AT&T",
  VZ: "버라이즌",
  TMUS: "T모바일",
  CMCSA: "컴캐스트",
  CHTR: "차터",
  ROKU: "로쿠",
  SPOT: "스포티파이",
  SNAP: "스냅",
  PINS: "핀터레스트",
  RBLX: "로블록스",

  // --- 에너지 / 소재 ---
  XOM: "엑슨모빌",
  CVX: "셰브론",
  COP: "코노코필립스",
  OXY: "옥시덴탈",
  SLB: "슐럼버거",
  EOG: "EOG 리소시스",
  PSX: "필립스 66",
  MPC: "마라톤 페트롤리엄",
  VLO: "발레로",
  LIN: "린데",
  APD: "에어프로덕츠",
  FCX: "프리포트-맥모란",
  NEM: "뉴몬트",

  // --- 산업 / 유틸리티 ---
  CAT: "캐터필러",
  DE: "디어",
  MMM: "3M",
  HON: "하니웰",
  ETN: "이튼",
  PH: "파커하니핀",
  EMR: "에머슨 일렉트릭",
  DUK: "듀크에너지",
  NEE: "넥스트에라에너지",
  SO: "서던 컴퍼니",

  // --- 부동산 ---
  AMT: "아메리칸타워",
  PLD: "프롤로지스",
  EQIX: "에퀴닉스",

  // --- 중국 ADR ---
  BABA: "알리바바",
  JD: "징둥",
  PDD: "핀둬둬 (테무)",
  BIDU: "바이두",
  NTES: "넷이즈",
  TME: "텐센트뮤직",

  // --- 기타 핫 ---
  PLTR: "팔란티어",
  MSTR: "마이크로스트래티지",
  SHOP: "쇼피파이",
  ZM: "줌",
  DOCU: "도큐사인",
  TWLO: "트윌리오",
  PATH: "유아이패스",
  RIOT: "라이엇 블록체인",
  MARA: "마라톤 디지털",
  ENPH: "인페이즈 에너지",
  SEDG: "솔라엣지",
  FSLR: "퍼스트 솔라",

  // --- ETF ---
  SPY: "S&P 500 ETF (SPDR)",
  VOO: "S&P 500 ETF (뱅가드)",
  IVV: "S&P 500 ETF (iShares)",
  QQQ: "나스닥 100 ETF",
  QQQM: "나스닥 100 ETF (저비용)",
  DIA: "다우존스 ETF",
  VTI: "미국 전체주식 ETF",
  VT: "글로벌 전체주식 ETF",
  VXUS: "미국 외 글로벌 ETF",
  SCHD: "배당성장 ETF",
  VIG: "배당성장 ETF (뱅가드)",
  VYM: "고배당 ETF",
  JEPI: "JP모건 옵션 인컴 ETF",
  JEPQ: "JP모건 나스닥 옵션 인컴 ETF",

  // 레버리지
  TQQQ: "나스닥 100 3배 레버리지",
  SQQQ: "나스닥 100 3배 인버스",
  UPRO: "S&P 500 3배 레버리지",
  SPXU: "S&P 500 3배 인버스",
  SPXL: "S&P 500 3배 레버리지 (Direxion)",
  SPXS: "S&P 500 3배 인버스 (Direxion)",
  SOXL: "반도체 3배 레버리지",
  SOXS: "반도체 3배 인버스",
  LABU: "바이오 3배 레버리지",
  LABD: "바이오 3배 인버스",
  TNA: "스몰캡 3배 레버리지",
  TZA: "스몰캡 3배 인버스",
  FAS: "금융 3배 레버리지",
  FAZ: "금융 3배 인버스",
  YINN: "중국 3배 레버리지",
  YANG: "중국 3배 인버스",
  NUGT: "금광 2배 레버리지",
  DUST: "금광 2배 인버스",
  JNUG: "주니어금광 2배 레버리지",
  JDST: "주니어금광 2배 인버스",
  GUSH: "원유E&P 2배 레버리지",
  DRIP: "원유E&P 2배 인버스",
  UCO: "원유 2배 레버리지",
  SCO: "원유 2배 인버스",
  BOIL: "천연가스 2배 레버리지",
  KOLD: "천연가스 2배 인버스",
  TMF: "20년+ 국채 3배 레버리지",
  TMV: "20년+ 국채 3배 인버스",

  // VIX
  UVXY: "VIX 단기선물 1.5배",
  SVXY: "VIX 단기선물 인버스",
  VIXY: "VIX 단기선물",
  UVIX: "VIX 2배 레버리지",
  SVIX: "VIX 인버스",

  // 섹터
  XLK: "테크 섹터 SPDR",
  XLF: "금융 섹터 SPDR",
  XLE: "에너지 섹터 SPDR",
  XLV: "헬스케어 섹터 SPDR",
  XLY: "임의소비 섹터 SPDR",
  XLP: "필수소비 섹터 SPDR",
  XLI: "산업 섹터 SPDR",
  XLU: "유틸리티 섹터 SPDR",
  XLB: "소재 섹터 SPDR",
  XLRE: "부동산 섹터 SPDR",
  XLC: "커뮤니케이션 섹터 SPDR",
  SMH: "반도체 ETF (VanEck)",
  SOXX: "반도체 ETF (iShares)",

  // 채권
  TLT: "미국 20년+ 국채 ETF",
  IEF: "미국 7~10년 국채 ETF",
  SHY: "미국 1~3년 국채 ETF",
  HYG: "하이일드 채권 ETF",
  JNK: "하이일드 채권 ETF (SPDR)",
  LQD: "투자등급 회사채 ETF",
  BND: "미국 전체채권 ETF",
  AGG: "미국 전체채권 ETF (iShares)",
  TIP: "물가연동채권 ETF",

  // 글로벌 / 테마
  VWO: "신흥국 ETF (뱅가드)",
  IEMG: "신흥국 ETF (iShares)",
  FXI: "중국 대형주 ETF",
  MCHI: "중국 전체 ETF",
  KWEB: "중국 인터넷 ETF",
  EWJ: "일본 ETF",
  INDA: "인도 ETF",
  EWZ: "브라질 ETF",
  ARKK: "ARK 이노베이션",
  ARKG: "ARK 지노믹스",
  ARKQ: "ARK 로보틱스",
  ARKW: "ARK 차세대 인터넷",
  ARKF: "ARK 핀테크",
  ARKX: "ARK 우주탐사",
  TAN: "태양광 ETF",
  URA: "우라늄 ETF",
  LIT: "리튬 & 배터리 ETF",

  // 금속 / 원자재
  GLD: "금 ETF (SPDR)",
  IAU: "금 ETF (iShares)",
  SLV: "은 ETF",
  USO: "원유 ETF",
  UNG: "천연가스 ETF",
  BITO: "비트코인 선물 ETF",
  IBIT: "iShares 비트코인 ETF",
  GBTC: "그레이스케일 비트코인 ETF",
};

export function prettyUSName(ticker: string, original: string): string {
  const kr = US_KR_NAMES[ticker];
  if (kr) return kr;
  // SEC가 대문자로 주는 이름을 단어 앞글자만 대문자 처리해 덜 투박하게
  if (original === original.toUpperCase()) {
    return original
      .toLowerCase()
      .replace(/\b[a-z]/g, (c) => c.toUpperCase())
      .replace(/\bInc\b/g, "Inc.")
      .replace(/\bCorp\b/g, "Corp.")
      .replace(/\bLtd\b/g, "Ltd.")
      .replace(/\bCo\b/g, "Co.");
  }
  return original;
}
