// AUTO-GENERATED by scripts/fetch-yahoo-financials.py — GitHub Actions 에서 갱신
// 빌드시 placeholder.
export const YAHOO_FINANCIAL_DATA: Record<
  string,
  Partial<{
    trailingPE: number | null;
    forwardPE: number | null;
    priceToBook: number | null;
    returnOnEquity: number | null;
    operatingMargins: number | null;
    profitMargins: number | null;
    grossMargins: number | null;
    debtToEquity: number | null;
    trailingEps: number | null;
    forwardEps: number | null;
    marketCap: number | null;
    dividendYield: number | null;
    trailingAnnualDividendYield: number | null;
    beta: number | null;
    earningsQuarterlyGrowth: number | null;
    revenueQuarterlyGrowth: number | null;
    earningsGrowth: number | null;
    revenueGrowth: number | null;
    fiftyTwoWeekHigh: number | null;
    fiftyTwoWeekLow: number | null;
    sharesOutstanding: number | null;
  }>
> = {};
