title: eloan.kr
description: 디딤돌대출 계산기 & 금융정보
url: "https://eloan.kr"
baseurl: ""

permalink: /blog/:title/

plugins:
  - jekyll-seo-tag

include:
  - sitemap.xml

exclude:
  - README.md
  - requirements.txt
  - auto_writer.py
  - auto_settings.json
  - admin.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
