#!/usr/bin/env python3
"""
미국 SEC EDGAR 공시 데이터 일괄 수집.
GitHub Actions runner 에서 실행 → src/lib/sec-filings-data.ts 갱신.

EDGAR 는 인증 불필요. User-Agent 헤더만 요구 (Fair Access 정책).
"""

from __future__ import annotations

import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

OUT = Path("src/lib/sec-filings-data.ts")
USER_AGENT = "eloan.kr admin@eloan.kr"
CONCURRENCY = 5  # EDGAR 권장: 10 req/sec/IP 이하 → 안전 영역
REQUEST_DELAY_SEC = 0.1
MAX_PER_TICKER = 15

# 보여줄 의미 있는 form 종류
KEEP_FORMS = {
    "10-K",      # 연간 보고서
    "10-Q",      # 분기 보고서
    "8-K",       # 주요 사건 보고서
    "20-F",      # 외국 사업자 연간 보고서
    "6-K",       # 외국 사업자 분기 보고서
    "DEF 14A",   # 위임장 (주주총회)
    "S-1",       # 신규 증권 등록
    "S-3",       # 단축 등록
    "S-4",       # 합병·인수
    "424B2",     # 모집 안내
    "424B4",
    "424B5",
    "SC 13D",    # 5% 이상 지분 (적극적)
    "SC 13G",    # 5% 이상 지분 (수동적)
    "13F-HR",    # 기관 보유 보고
    "4",         # 내부자 거래
}


def http_get_json(url: str) -> dict:
    req = Request(url, headers={"User-Agent": USER_AGENT, "Accept": "application/json"})
    with urlopen(req, timeout=30) as r:
        return json.load(r)


def fetch_cik_map() -> dict[str, str]:
    """ticker → 10자리 zero-padded CIK."""
    data = http_get_json("https://www.sec.gov/files/company_tickers.json")
    out: dict[str, str] = {}
    for row in data.values():
        ticker = row.get("ticker", "").strip().upper()
        cik = row.get("cik_str")
        if ticker and isinstance(cik, int):
            out[ticker] = str(cik).zfill(10)
    return out


def fetch_filings(ticker: str, cik: str) -> list[dict]:
    try:
        data = http_get_json(f"https://data.sec.gov/submissions/CIK{cik}.json")
        recent = data.get("filings", {}).get("recent", {})
        forms = recent.get("form", [])
        dates = recent.get("filingDate", [])
        accs = recent.get("accessionNumber", [])
        primaries = recent.get("primaryDocument", [])
        result = []
        for i in range(len(forms)):
            form = forms[i]
            if form not in KEEP_FORMS:
                continue
            acc_clean = accs[i].replace("-", "")
            url = (
                f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/{acc_clean}/{primaries[i]}"
            )
            result.append({
                "date": dates[i],
                "form": form,
                "url": url,
            })
            if len(result) >= MAX_PER_TICKER:
                break
        return result
    except Exception:
        return []


def write_output(payload: dict) -> None:
    banner = (
        f"// AUTO-GENERATED by scripts/fetch-sec-filings.py at "
        f"{datetime.now(timezone.utc).date().isoformat()}\n"
    )
    type_str = "Record<string, Array<{ date: string; form: string; url: string }>>"
    body = (
        f"export const SEC_FILINGS_DATA: {type_str} = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(banner + body, encoding="utf-8")


def main() -> None:
    print("[sec] fetching ticker→CIK map...")
    cik_map = fetch_cik_map()
    tickers = sorted(cik_map.keys())
    print(f"[sec] {len(tickers)} tickers — fetching filings")

    results: dict[str, list[dict]] = {}
    t0 = time.time()
    done = 0

    def work(t: str) -> tuple[str, list[dict]]:
        time.sleep(REQUEST_DELAY_SEC)
        return t, fetch_filings(t, cik_map[t])

    with ThreadPoolExecutor(max_workers=CONCURRENCY) as ex:
        futs = {ex.submit(work, t): t for t in tickers}
        for fut in as_completed(futs):
            sym, filings = fut.result()
            done += 1
            if filings:
                results[sym] = filings
            if done % 500 == 0:
                elapsed = int(time.time() - t0)
                print(f"[sec] {done}/{len(tickers)} ({elapsed}s, {len(results)} kept)")

    print(f"[sec] done: {len(results)}/{len(tickers)} tickers with filings")
    write_output(results)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[sec] unexpected: {e}", file=sys.stderr)
        if not OUT.exists():
            write_output({})
        sys.exit(0)
