#!/usr/bin/env python3
"""
미국 NYSE+NASDAQ 상장 전 종목의 야후 파이낸스 재무 데이터 일괄 수집.
GitHub Actions runner (비차단 IP) 에서 실행 → src/lib/yahoo-financial-data.ts 갱신.

yfinance 가 야후의 crumb cookie 인증을 자동 처리.
"""

from __future__ import annotations

import json
import logging
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

import yfinance as yf

# yfinance 의 404/Quote not found 등 내장 로그 무음 처리 — 6000개 중
# 상장폐지·OTC 등 무효 ticker 가 다수라 노이즈만 많음
logging.getLogger("yfinance").setLevel(logging.CRITICAL)
logging.getLogger("urllib3").setLevel(logging.CRITICAL)

OUT = Path("src/lib/yahoo-financial-data.ts")
CONCURRENCY = 4  # 야후 차단 회피 — 보수적 동시 처리
REQUEST_DELAY_SEC = 0.1
MAX_RETRIES = 3  # 429/throttle 시 재시도

# 수집할 필드 (yfinance Ticker.info 키 기준)
FIELDS = [
    "trailingPE",
    "forwardPE",
    "priceToBook",
    "returnOnEquity",
    "operatingMargins",
    "profitMargins",
    "grossMargins",
    "debtToEquity",
    "trailingEps",
    "forwardEps",
    "marketCap",
    "dividendYield",
    "trailingAnnualDividendYield",
    "beta",
    "earningsQuarterlyGrowth",
    "revenueQuarterlyGrowth",
    "earningsGrowth",
    "revenueGrowth",
    "fiftyTwoWeekHigh",
    "fiftyTwoWeekLow",
    "sharesOutstanding",
]

NASDAQ_LIST_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt"
OTHER_LIST_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"


def fetch_text(url: str) -> str:
    req = Request(url, headers={"User-Agent": "Mozilla/5.0 (compatible; eloan-data-fetcher)"})
    with urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", errors="replace")


def get_us_tickers() -> list[str]:
    """NASDAQ Trader 의 공식 종목 리스트 (NASDAQ + NYSE/AMEX 등)."""
    tickers: list[str] = []
    for url in (NASDAQ_LIST_URL, OTHER_LIST_URL):
        try:
            text = fetch_text(url)
        except Exception as e:
            print(f"[us-tickers] {url} failed: {e}", file=sys.stderr)
            continue
        lines = text.splitlines()
        if not lines:
            continue
        header = lines[0].split("|")
        try:
            sym_idx = header.index("Symbol") if "Symbol" in header else header.index("ACT Symbol")
        except ValueError:
            sym_idx = 0
        try:
            test_idx = header.index("Test Issue")
        except ValueError:
            test_idx = None
        for line in lines[1:]:
            if not line or line.startswith("File Creation Time"):
                continue
            parts = line.split("|")
            if len(parts) <= sym_idx:
                continue
            sym = parts[sym_idx].strip()
            if not sym or " " in sym or "$" in sym or "." in sym:
                # warrant / 우선주 / 펀드 단위 등 제외
                continue
            if test_idx is not None and len(parts) > test_idx and parts[test_idx].strip() == "Y":
                continue
            tickers.append(sym)
    # 중복 제거 + 정렬
    return sorted(set(tickers))


def fetch_one(symbol: str) -> tuple[str, dict | None]:
    last_err = None
    for attempt in range(MAX_RETRIES):
        try:
            info = yf.Ticker(symbol).info
            if not info or not isinstance(info, dict):
                return symbol, None
            data = {}
            has_value = False
            for k in FIELDS:
                v = info.get(k)
                if v is None or (isinstance(v, float) and (v != v)):  # NaN
                    data[k] = None
                else:
                    data[k] = v
                    has_value = True
            if not has_value:
                return symbol, None
            return symbol, data
        except Exception as e:
            last_err = e
            msg = str(e).lower()
            # 429 / throttle → backoff 후 재시도
            if "429" in msg or "rate" in msg or "throttl" in msg:
                time.sleep(2 ** attempt)  # 1s, 2s, 4s
                continue
            # 기타 에러는 즉시 포기
            return symbol, None
    return symbol, None


def write_output(payload: dict) -> None:
    banner = (
        f"// AUTO-GENERATED by scripts/fetch-yahoo-financials.py at "
        f"{datetime.now(timezone.utc).date().isoformat()}\n"
    )
    type_str = (
        "Record<string, Partial<{ "
        + "; ".join(f"{k}: number | null" for k in FIELDS)
        + " }>>"
    )
    body = (
        f"export const YAHOO_FINANCIAL_DATA: {type_str} = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(banner + body, encoding="utf-8")


def main() -> None:
    print("[yahoo] fetching US ticker list...")
    tickers = get_us_tickers()
    print(f"[yahoo] {len(tickers)} tickers — fetching financials")

    results: dict[str, dict] = {}
    t0 = time.time()
    done = 0

    with ThreadPoolExecutor(max_workers=CONCURRENCY) as ex:
        futs = {ex.submit(fetch_one, t): t for t in tickers}
        for fut in as_completed(futs):
            sym, data = fut.result()
            done += 1
            if data:
                results[sym] = data
            if done % 200 == 0:
                elapsed = int(time.time() - t0)
                print(f"[yahoo] {done}/{len(tickers)} ({elapsed}s, {len(results)} kept)")
            if REQUEST_DELAY_SEC > 0:
                time.sleep(REQUEST_DELAY_SEC)

    print(f"[yahoo] done: {len(results)}/{len(tickers)} tickers kept")
    write_output(results)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[yahoo] unexpected: {e}", file=sys.stderr)
        # 빈 데이터로라도 placeholder 갱신해 빌드 안 깨지게
        if not OUT.exists():
            write_output({})
        sys.exit(0)
